### ISSUE TITLE
go to next search page

### ISSUE THREAD

**Issue by muralikodali** [ajimix/raindrop-search#1]
it is showing only 8 results. 
how to move on to next page for search results ?
can we increase the maximum number of search results?

where is the location of database ?

if you give some configurable options to the app, it would be more useful.

**Comment by ajimix** [comment]
@muralikodali when you run `rds --configure` it will ask you how many max results you want to show. By default is 8 but you can change it to any number you want.

At the moment there is no pagination as I usually query for something which returns a small number of results so I never needed pagination. But if you know how to code you can submit a pull request to implement pagination and I will merge it.

The database file is saved in the same path where the app is installed which you can figure out by running `which rds` in your terminal. This will print something like... `/Users/abc/.node/bin/rds` that is the bin path, from there you can find out the actual path which in the case above it will be something like `/Users/abc/.node/lib/node_modules/raindrop_search/`

I hope it helps. I'm closing the issue.
