### ISSUE TITLE
invalid raindrop response 401

### ISSUE THREAD

**Issue by muralikodali** [ajimix/raindrop-search#2]
```rds --cache``` giving the following output : 

```
Fetching Raindrop links page 1
Fetching Raindrop links page 2
Fetching Raindrop links page 3
Fetching Raindrop links page 4
Fetching Raindrop links page 5
Error: Invalid Raindrop response 401
    at /home/xxxx/asdf/installs/nodejs/20.9.0/lib/node_modules/raindrop-search/src/cache-bookmarks.js:68:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async fetchPages (/home/xxxx/asdf/installs/nodejs/20.9.0/lib/node_modules/raindrop-search/src/cache-bookmarks.js:102:5)
Cache successful
```
node version: 20.9.0

**Comment by ajimix** [comment]
@muralikodali did you follow the Readme setup instructions, created the app in raindrop and then configured the app as per the Readme?

**Comment by muralikodali** [comment]
i have configured the program as suggested by you.
the only difference is, i have upgraded the node version from 19.x.x to 20.9.0.

**Comment by ajimix** [comment]
@muralikodali I just tested myself with node 20.9.0 and it worked properly. Also, the error you shared comes directly from Raindrop 401, which is wrong authentication. 

I suggest you uninstall `npm uninstall -g raindrop-search` and install again `npm i -g raindrop-search` and then run the configuration again. Make sure you use the test token from raindrop.

**Comment by muralikodali** [comment]
@ajimix thanks for your suggestion.

checked the test token at raindrop.io site. some how it is removed without my intervention.

after creating a new test token and configuring raindrop-search, now the program is working as expected.
